<?php

namespace App;


class StatInterface
{
    // quirks
    const ITEM_MOD_ARMOR = -1;
    const ITEM_MOD_BASE_STATS = -2;
    const ITEM_MOD_BASE_STATS_RELATIV = -3;
    const ITEM_MOD_AGILITY_RELATIV = -4;
    const ITEM_MOD_STRENGTH_RELATIV = -5;
    const ITEM_MOD_INTELLECT_RELATIV = -6;
    const ITEM_MOD_SPIRIT_RELATIV = -7;
    const ITEM_MOD_STAMINA_RELATIV = -8;
    const ITEM_MOD_ARMOR_RELATIV = -9;
    const ITEM_MOD_MEELE_CRIT_PERCENT = -10;
    const ITEM_MOD_CASTER_CRIT_PERCENT = -11;
    const ITEM_MOD_HEAL_CRIT_PERCENT = -12;
    const ITEM_MOD_CRIT_MOD = -13;
    #const ITEM_MOD_STUN_DURATION = -14;
    #const ITEM_MOD_SILENCE_DURATION = -15;

    //trinity stats
    const ITEM_MOD_MANA = 0;
    const ITEM_MOD_HEALTH = 1;
    const ITEM_MOD_AGILITY = 3;
    const ITEM_MOD_STRENGTH = 4;
    const ITEM_MOD_INTELLECT = 5;
    const ITEM_MOD_SPIRIT = 6;
    const ITEM_MOD_STAMINA = 7;
    const ITEM_MOD_DEFENSE_SKILL_RATING = 12;
    const ITEM_MOD_DODGE_RATING = 13;
    const ITEM_MOD_PARRY_RATING = 14;
    const ITEM_MOD_BLOCK_RATING = 15;
    const ITEM_MOD_HIT_MELEE_RATING = 16;
    const ITEM_MOD_HIT_RANGED_RATING = 17;
    const ITEM_MOD_HIT_SPELL_RATING = 18;
    const ITEM_MOD_CRIT_MELEE_RATING = 29;
    const ITEM_MOD_CRIT_RANGED_RATING = 20;
    const ITEM_MOD_CRIT_SPELL_RATING = 21;
    const ITEM_MOD_HIT_TAKEN_MELEE_RATING = 22;
    const ITEM_MOD_HIT_TAKEN_RANGED_RATING = 23;
    const ITEM_MOD_HIT_TAKEN_SPELL_RATING = 24;
    const ITEM_MOD_CRIT_TAKEN_MELEE_RATING = 25;
    const ITEM_MOD_CRIT_TAKEN_RANGED_RATING = 26;
    const ITEM_MOD_CRIT_TAKEN_SPELL_RATING = 27;
    const ITEM_MOD_HASTE_MELEE_RATING = 28;
    const ITEM_MOD_HASTE_RANGED_RATING = 29;
    const ITEM_MOD_HASTE_SPELL_RATING = 30;
    const ITEM_MOD_HIT_RATING = 31;
    const ITEM_MOD_CRIT_RATING = 32;
    const ITEM_MOD_HIT_TAKEN_RATING = 33;
    const ITEM_MOD_CRIT_TAKEN_RATING = 34;
    const ITEM_MOD_RESILIENCE_RATING = 35;
    const ITEM_MOD_HASTE_RATING = 36;
    const ITEM_MOD_EXPERTISE_RATING = 37;
    const ITEM_MOD_ATTACK_POWER = 38;
    const ITEM_MOD_RANGED_ATTACK_POWER = 39;
    const ITEM_MOD_FERAL_ATTACK_POWER = 40;
    const ITEM_MOD_SPELL_HEALING_DONE = 41;
    const ITEM_MOD_SPELL_DAMAGE_DONE = 42;
    const ITEM_MOD_MANA_REGENERATION = 43;
    const ITEM_MOD_ARMOR_PENETRATION_RATING = 44;
    const ITEM_MOD_SPELL_POWER = 45;
    const ITEM_MOD_HEALTH_REGEN = 46;
    const ITEM_MOD_SPELL_PENETRATION = 47;
    const ITEM_MOD_BLOCK_VALUE = 48;

} 